import = ["~/.config/alacritty/themes/tokyonight/tokyonight_moon.toml"]

[window]
padding = { x = 10, y = 5 }
dynamic_padding = true
#decorations = "transparent"
#startup_mode = "Maximized"

[scrolling]
history = 10000
multiplier = 10

[font]
size = 14
normal = { family = "VictorMono Nerd Font", style = "Regular" }
bold = { family = "VictorMono Nerd Font", style = "Bold" }
italic = { family = "VictorMono Nerd Font", style = "Italic" }
bold_italic = { family = "VictorMono Nerd Font", style = "Bold Italic" }

[shell]
program = "/opt/homebrew/bin/fish"
args = ["-l", "-c", 'zellij --layout compact attach --index 0 --create']
#args = ["-l", "-c", 'zellij attach --index 0 --create']

[env]
# TERM = "alacritty"
TERM = "xterm-256color"
